program: ./src/models/train_model_sweep.py
method: random
name: sweep

metric:
  goal: maximize
  name: val_acc

parameters:
  model_type: # fast or precise
    value: "precise"

  training_type: # lightning or normal
    value: "lightning"

  image_size_x: 
    value: 256

  image_size_y: 
    value: 256

  batch_size: 
    values: [16,32,64]

  lr:
    min: 0.00001
    max: 0.001

  epochs:
    values: [5, 10, 15]

  limit_batches:
    values: [1]

  patience:
    value: 10